Module3 task1
htmlacademy-ecmascript/488893-cinemaddict-17 pull request #5
Opened 2022-05-18 04:03 UTC by IoanKing

2022-05-18 20:28 UTC, KletskovG requested changes

2022-05-18 20:28 UTC, KletskovG commented on src/presenter/boad-presenter.js
> +      for (let i = 0; i < additionalListCount; i++) {
Что-то меня смущает, что этот кусок кода повторяется 2 раза

На первый взгляд кажется, что этот цикл выполнится в любом случае. 2 раза выполнится, если выполнение зайдет в else, и 1 раз, если в if 

Тут точно все ок?

2022-05-18 20:28 UTC, KletskovG commented on src/render.js
> +  const element = component.element;
`const element = component.element` -> `const { element } = component`

Можно не повторять element, если использовать деструктуризацию

2022-05-19 04:54 UTC, IoanKing commented on src/presenter/boad-presenter.js
> +      for (let i = 0; i < additionalListCount; i++) {
Сделал так что бы блоки "Top rated" и  "Most commented" не вводились когда карточек фильмов нету.
Одного сообщения о том что БД фильмов пуста достаточно. Убрал лишние циклы.

2022-05-19 04:54 UTC, IoanKing commented on src/presenter/boad-presenter.js
> +      if (evt.key === 'Escape' || evt.key === 'Esc') {
Вынес в отдельную функцию.

2022-05-19 04:54 UTC, IoanKing commented on src/render.js
> +  const element = component.element;
Поправил.

2022-05-19 19:43 UTC, merged